### ISSUE TITLE
enclosure_groups.create() Does not take valid data and returns JSON error

### ISSUE THREAD

**Issue by Georgimi** [HewlettPackard/oneview-python#84] opened 2020-08-28 07:41 UTC
Tried the examples in enclosure_groups 

...

_data = {
    "name": "Enclosure Group 1",
    "ipAddressingMode": "External",
    "interconnectBayMappings":
        [
            {
                "interconnectBay": 1,
            },
            {
                "interconnectBay": 2,
            },
            {
                "interconnectBay": 3,
            },
            {
                "interconnectBay": 4,
            },
            {
                "interconnectBay": 5,
            },
            {
                "interconnectBay": 6,
            }
        ]
}_

This should create an empty EG. 

Used this to create it
_enclosure_groups.create(data)_

Gives JSON error:
_hpOneView.exceptions.HPOneViewException: ('Unrecognized JSON field.', {'errorCode': 'UNRECOGNIZED_JSON_FIELD', 'message': 'Unrecognized JSON field.', 'details': 'The field named type near line 1, column 52 is not a valid field in this JSON object.', 'messageParameters': [], 'recommendedActions': ['Check the valid fields for this JSON object and remove or correct the unrecognized field.'], 'errorSource': None, 'nestedErrors': [], 'data': {}})_

Seems like the REST API expects some different information.

Also tried the examples from the REST API Reference 1800:
_{
    "name": "eg-2-lig-sideA-sideB-bayset-2",
    "ipAddressingMode": "External",
    "interconnectBayMappings":
    [
        {
            "interconnectBay": 2,
            "logicalInterconnectGroupUri": "/rest/logical-interconnect-groups/7d860164-266b-408a-9ceb-59be6f27b3f8"
        },
        {
            "interconnectBay": 5,
            "logicalInterconnectGroupUri": "/rest/logical-interconnect-groups/74942c3d-e132-4976-bf5f-fd2967c3f47d"
        },
        {
            "enclosureIndex": 1,
            "interconnectBay": 1,
            "logicalInterconnectGroupUri": "/rest/sas-logical-interconnect-groups/aeef7314-527d-4053-868c-17b87df1b57c"
        },
        {
            "enclosureIndex": 2,
            "interconnectBay": 1,
            "logicalInterconnectGroupUri": "/rest/sas-logical-interconnect-groups/beef7314-527d-4053-868c-17b87df1b57a"
        },
        {
            "enclosureIndex": 2,
            "interconnectBay": 4,
            "logicalInterconnectGroupUri": "/rest/sas-logical-interconnect-groups/beef7314-527d-4053-868c-17b87df1b57a"
        },

    ],
    "enclosureCount": 3
}_

As this does not works as well. Same JSON error i suspect there is some problem with the create(data) itself. 
Have seens this with the networks.create(data) as well ... but was able to workaround this.

Also ... Logical_Interconnects.create(data) works just fine ..

Regards

**Comment by Georgimi** [comment] 2020-08-28 08:45
Update: Tried the converttopython examples as well, to see if I am missing a field or something. 
But it looks like that this one is broken by this function (enclosure_groups.update()) as well.

FYI: Using OneView 5.30

**Comment by yuvirani** [comment] 2020-08-28 13:21
@Georgimi,
The root cause of this issue is from Oneview EnclosureGroup API.  The python library is including "type" in the JSON payload since type attribute is one of the default lib attribute collection. Hence, made the changes to our python library to remove this field. Please checkout the below branch into your python repository and do pip install .

https://github.com/HewlettPackard/oneview-python/tree/EnclosureType where branch name = EnclosureType

Please do let us know if you face any issues.

**Comment by yuvirani** [comment] 2020-09-04 12:41
Please free to reopen this issue if the above issue is not resolved in any case.

**Closed by yuvirani** 2020-09-04 12:41 UTC

**Comment by saketmarodia** [comment] 2020-10-30 06:43
I am facing the same issue while EG creation, The JSON is valid and Creates a EG if the REST endpoint.
        uri2="https://"+IP+"/rest/enclosure-groups"
        response2 = requests.post(uri2,verify=False,json=EG_data,headers=Headers)

But it gives an error when using the Python SDK. can you please reopen the issue
