### ISSUE TITLE
TypeError running examples

### ISSUE THREAD

**Issue by agdunkley** [HewlettPackard/oneview-python#25] opened 2020-02-28 14:22 UTC
I am trying to learn the oneview SDK as I have needing to interface with iLO controls, and which ever examples code I try and runm I always get the following error:

TypeError: string indices must be integers, not unicode.  

I am using the latest SDK from the master branch, my ILO is is DL360 G9,  & ILO firmware is 2.55, Aug  16 2017,

**Comment by soodpr** [comment] 2020-02-28 14:42
@agdunkley - Can you please share the complete Traceback to identify the line where you are getting this error.

**Comment by agdunkley** [comment] 2020-02-28 15:45
This is the full trace.  The example I am trialling is the most simple I can find - versions.py

Traceback (most recent call last):
  File "versions.py", line 33, in <module>
    oneview_client = OneViewClient(config)
  File "build/bdist.linux-x86_64/egg/hpOneView/oneview_client.py", line 122, in __init__
    self.__connection.login(config["credentials"])
  File "build/bdist.linux-x86_64/egg/hpOneView/connection.py", line 462, in login
    auth = body['sessionID']
TypeError: string indices must be integers, not unicode

 I have been diving into this a bit more, and what I think is happening is the the response is a 307, which isnt being handled.  The redirect is happening because the URI are /rest/login-sessions, whereas it should be /rest/v1/login-sessions.

If I change the uri table to use the correct URIs, I get:

Traceback (most recent call last):
  File "server_hardware.py", line 42, in <module>
    oneview_client = OneViewClient(config)
  File "/home/ansible/alan/wa/test/oneview_client.py", line 122, in __init__
    self.__connection.login(config["credentials"])
  File "/home/ansible/alan/wa/test/connection.py", line 453, in login
    raise(HPOneViewException('Failure during login attempt.\n %s' % traceback.format_exc()))
HPOneViewException: Failure during login attempt.
Traceback (most recent call last):
  File "/home/ansible/alan/wa/test/connection.py", line 451, in login
    self.validateVersion()
  File "/home/ansible/alan/wa/test/connection.py", line 75, in validateVersion
    version = self.get(uri['version'])
  File "/home/ansible/alan/wa/test/connection.py", line 339, in get
    raise HPOneViewException(body)
HPOneViewException: (None, {u'Type': u'ExtendedError.1.0.0', u'Messages': [{u'MessageID': u'Base.0.10.NoValidSession'}], u'error': {u'code': u'iLO.0.10.ExtendedInfo', u'message': u'See @Message.ExtendedInfo for more information.', u'@Message.ExtendedInfo': [{u'MessageID': u'Base.0.10.NoValidSession'}]}})

**Comment by soodpr** [comment] 2020-02-28 16:00
@agdunkley - May i know how you are initializing the OneViewClient via config dictionary or try_load_from_file method?

**Comment by agdunkley** [comment] 2020-02-28 16:09
Using the try_load method, file contents is:
{
  "ip": "xx.xx.xx.xx",
  "image_streamer_ip": "",
  "api_version": 800,
  "ssl_certificate": "",
  "credentials": {
    "userName": "Administrator",
    "authLoginDomain": "",
    "password": "XXXXXXXX",
    "sessionID": ""
  },
  "enclosure_hostname": "",
  "enclosure_username": "",
  "enclosure_password": "",
  "enclosure_group_uri": "",
  "server_mpHostsAndRanges": [],
  "server_hostname": "",
  "server_username": "",
  "server_password": "",
  "storage_system_hostname": "",
  "storage_system_username": "",
  "storage_system_password": "",
  "power_device_hostname": "",
  "power_device_username": "",
  "power_device_password": ""
}

**Comment by soodpr** [comment] 2020-02-28 16:26
@agdunkley - I am hoping your config file is present in the same path from where you are running your example code. If not, please try below code to initialize the OneViewClient.
config = ''
config = try_load_from_file(config, file_name='<path_to_config.json_file>')
oneview_client = OneViewClient(config)

**Comment by agdunkley** [comment] 2020-02-28 18:13
Yes it is.  I copied the example code to a test directory, created my config.json file and run everything from within my test folder

**Comment by agdunkley** [comment] 2020-02-29 11:32
Yes it is, in a test directory with version.py from the examples directory and the config_load module

**Comment by VenkateshRavula** [comment] 2020-04-16 10:08
I have tried re-run of versions.py file and it went through fine without any issues. Not able to see the above mentioned issue.

**Comment by VenkateshRavula** [comment] 2020-06-11 07:05
We are not able to reproduce this issue and also I didn't find any ways to hit this issue. Since we didn't get back any response from you, we assume that the issue is fixed and closing this. Please feel free to reopen this if you still face the issue.

**Closed by VenkateshRavula** 2020-06-11 07:05 UTC
